spring:
  application:
    name: fintrend-ai-platform-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/fintrend
    username: fintrend_user
    password: fintrend_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080