services:
  db:
    image: postgres:15
    container_name: fintrend-postgres
    environment:
      POSTGRES_DB: fintrend
      POSTGRES_USER: fintrend_user
      POSTGRES_PASSWORD: fintrend_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
